### ISSUE TITLE
Comment in front of line causes crash

### ISSUE THREAD

**Issue by cole21771** [dennis-classes/se2832-lab-01-isosceles-aureo96#5]
If you leave a comment in front of the line like you were going to ignore it, it throws an exception and crashes.

**Input:**
\# 3 3 3 
**Expected Result:**
_Nothing is printed to the console_
**Actual Result:**
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextDouble(Scanner.java:2413)
	at TriangleAnalyzer.<init>(TriangleAnalyzer.java:140)
	at MainProgram.main(MainProgram.java:26)

**Comment by aureo96** [comment]
I fixed this issue now. Please feel free to test the application more!
